# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IDCardAPIExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IDCardAPIExample
  pod 'Alamofire', '~> 5.2'

  target 'IDCardAPIExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IDCardAPIExampleUITests' do
    # Pods for testing
  end

end
